version: "2.3"

volumes:
  nginx_config: {}
  nginx_releasenote: {}
  ldap_db: {}
  ldap_static: {}
  sonar_mysql_data: {}
  sonar_data: {}
  sonar_extensions: {}
  sonar_logs: {}
  jenkins_slave_home: {}
  jenkins_slave_sock: {}
  jenkins_home: {}
  jenkins_sock: {}
  nexus_sonatype_work: {}
  registry_certs: {}
  registry_data: {}

services:
  proxy:
    volumes:
      - nginx_config:/etc/nginx
      - nginx_releasenote:/usr/share/nginx/html

  ldap:
    volumes:
      - ldap_db:/var/lib/ldap
      - ldap_static:/etc/ldap
  
  sonar-mysql:
      volumes:
      - sonar_mysql_data:/var/lib/mysql 

  sonar:
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions 
      - sonar_logs:/opt/sonarqube/logs

  jenkins-slave:
    volumes:
      - jenkins_slave_home:/workspace
      - jenkins_slave_sock:/var/run/docker.sock

  jenkins:
    volumes:
      - jenkins_home:/var/jenkins_home 
      - jenkins_sock:/var/run/docker.sock

  nexus:
    volumes:
      - nexus_sonatype_work:/sonatype-work

  registry:
    volumes:
      - registry_certs:/certs
      - registry_data:/data


# gitlab:
#  volumes:
#    - gitlab_etc:/etc/gitlab
#    - gitlab_opt:/var/opt/gitlab
#    - gitlab_log:/var/log/gitlab